/*
 * mfm
 *
 * (C) 2017 Angelo Dureghello <angelo@sysam.it>
 *
 * This file is part of mfm application.
 *
 * mfm library is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * mfm is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with mfm.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Using  paomedia (Arnaud) icons 24x24.
 * https://github.com/paomedia/small-n-flat
 *
 */

const char * xpm_icon_trash[] = {
		"24 24 27 1",
		" 	c None",
		".	c #CCD0D2",
		"+	c #CDD1D3",
		"@	c #D1D5D7",
		"#	c #CFD2D5",
		"$	c #CDD0D3",
		"%	c #AAADAF",
		"&	c #CACDCF",
		"*	c #C7CBCD",
		"=	c #C4C8CA",
		"-	c #B8BCBE",
		";	c #ADB0B2",
		">	c #BABDC0",
		",	c #CACED0",
		"'	c #B7BBBD",
		")	c #B9BCBF",
		"!	c #ACAFB1",
		"~	c #B8BBBD",
		"{	c #BABDBF",
		"]	c #CBCFD1",
		"^	c #ACAEB0",
		"/	c #B9BDBF",
		"(	c #C8CBCD",
		"_	c #B6B9BB",
		":	c #C8CCCE",
		"<	c #BCC0C2",
		"[	c #CDD2D4",
		"        ........        ",
		"       ..      ..       ",
		"       .+      +.       ",
		"  @@@@@@@@@@@@@@@@@@@@  ",
		"  @@@@@@@@@@@@@@@@@@@@  ",
		"  @@@@@@@@@@@@@@@@@@@@  ",
		"  @#$$$$$$$$$$$$$$$$#@  ",
		"   %%%%%%%%%%%%%%%%%%   ",
		"   &&&&&&&&&&&&&&&&&&   ",
		"   ...*=*..==..*=*...   ",
		"   ..+-;>+,;;,+>;-+..   ",
		"   ..+';)+,!!,+);'+..   ",
		"   ..+';)+,!!,+);'+..   ",
		"   ..+';)+,!!,+);'+..   ",
		"   ..+';)+,!!,+);'+..   ",
		"   ..+';)+,!!,+);'+..   ",
		"   ..+';)+,!!,+);'+..   ",
		"   ..+';)+,!!,+);'+..   ",
		"   ..+';)+,!!,+);'+..   ",
		"   ..+';)+,!!,+);'+..   ",
		"   ..+~!{+]^^]+/!~+..   ",
		"   ...(_:.+<<+.:_(...   ",
		"   ....[...++...[....   ",
		"    ................    "
};

const char * xpm_icon_copy[] = {
		"24 24 45 1",
		" 	c None",
		".	c #FFB655",
		"+	c #FFB554",
		"@	c #FFAC3E",
		"#	c #FFA732",
		"$	c #FFA733",
		"%	c #FFB654",
		"&	c #FFAC3F",
		"*	c #FFA734",
		"=	c #FEA734",
		"-	c #F8BB62",
		";	c #CED8A8",
		">	c #D1D198",
		",	c #D1CE92",
		"'	c #D1CF93",
		")	c #D2CF93",
		"!	c #C5CE92",
		"~	c #AACD92",
		"{	c #FFB552",
		"]	c #EEC271",
		"^	c #93FFFF",
		"/	c #98FEFF",
		"(	c #9AFEFF",
		"_	c #7EFDFF",
		":	c #42FBFF",
		"<	c #0FDFE8",
		"[	c #EFC170",
		"}	c #96FEFF",
		"|	c #9BFBFF",
		"1	c #9DFBFF",
		"2	c #82FAFF",
		"3	c #48F9FF",
		"4	c #0FDEE6",
		"5	c #00D6DE",
		"6	c #00D7DF",
		"7	c #48F8FF",
		"8	c #11DFE7",
		"9	c #02D8E0",
		"0	c #47F8FF",
		"a	c #44F7FE",
		"b	c #46F8FF",
		"c	c #FFB553",
		"d	c #F0C16F",
		"e	c #E1CA88",
		"f	c #99FCFF",
		"  ......+@#$$$$$        ",
		"  ......+@#$$$$$        ",
		"  ......+@#$$$$$        ",
		"  ......+@#$$$$$        ",
		"  ......%&$***==        ",
		"  ....%-;>,'')!~        ",
		"  ....{]^////(_:<       ",
		"  ....{[}||||12345      ",
		"  ....{[}||||123456     ",
		"  ....{[}||||1234566    ",
		"  ....{[}||||12786999   ",
		"  ....{[}||||120aaaaaa  ",
		"  ....{[}||||120bbbbbb  ",
		"  ....{[}||||120bbbbbb  ",
		"  ....{[}||||120bbbbbb  ",
		"  ....{[}||||120bbbbbb  ",
		"  ....{[}||||120bbbbbb  ",
		"  ....cd}||||120bbbbbb  ",
		"       ef||||120bbbbbb  ",
		"        |||||120bbbbbb  ",
		"        |||||120bbbbbb  ",
		"        |||||120bbbbbb  ",
		"        |||||120bbbbbb  ",
		"        |||||120bbbbbb  "
};

/* XPM */
const char * xpm_icon_cut[] = {
		"24 24 48 1",
		" 	c None",
		".	c #BDDBFF",
		"+	c #9BC9FF",
		"@	c #BBDAFF",
		"#	c #9DCAFF",
		"$	c #ABD1FF",
		"%	c #B9D9FF",
		"&	c #9FCBFF",
		"*	c #BEDCFF",
		"=	c #AFD3FF",
		"-	c #A0CBFF",
		";	c #9AC9FF",
		">	c #B7D8FF",
		",	c #B6D8FF",
		"'	c #9AC8FF",
		")	c #A7D0FF",
		"!	c #BCDBFF",
		"~	c #2488FF",
		"{	c #2588FF",
		"]	c #469AFF",
		"^	c #8ABFFF",
		"/	c #B5D7FF",
		"(	c #BEDBFF",
		"_	c #C0DDFF",
		":	c #A5CBF9",
		"<	c #3984DD",
		"[	c #015ECE",
		"}	c #005ECE",
		"|	c #2086FF",
		"1	c #3B95FF",
		"2	c #9CCAFF",
		"3	c #B5D6FD",
		"4	c #1E72D6",
		"5	c #0059CC",
		"6	c #1F85FF",
		"7	c #6BAFFF",
		"8	c #ADD3FF",
		"9	c #C6E1FF",
		"0	c #5B9AE6",
		"a	c #005DCE",
		"b	c #2287FF",
		"c	c #4198FF",
		"d	c #A4CEFF",
		"e	c #C5E0FF",
		"f	c #2475D7",
		"g	c #1C71D5",
		"h	c #4097FF",
		"i	c #186ED4",
		"       .        +       ",
		"      ..        ++      ",
		"     ....      ++++     ",
		"     .....    +++++     ",
		"     .....    ++++++    ",
		"     ......  ++++++     ",
		"     ......  ++++++     ",
		"      .....@#+++++      ",
		"      ......$+++++      ",
		"       .....%&+++       ",
		"       .....*=+++       ",
		"        .....*-;        ",
		"         .....>         ",
		"         ,.....         ",
		"        ')!....@        ",
		"   ~~~~{]^/(._:<[}}}}   ",
		"  ~~~  ~|12.*345}  }}}  ",
		"  ~~    ~67890a}    }}  ",
		" ~~      bcdef}      }} ",
		" ~~      b1  g}      }} ",
		"  ~~     bh  i}}    }}} ",
		"  ~~    ~~    }}    }}  ",
		"   ~~~~~~     }}}}}}}   ",
		"    ~~~~        }}}}    "
};

const char * xpm_icon_paste[] = {
		"24 24 55 1",
		" 	c None",
		".	c #FFDA44",
		"+	c #FFB655",
		"@	c #FFB356",
		"#	c #FFD447",
		"$	c #FFC23C",
		"%	c #FFA532",
		"&	c #FFA733",
		"*	c #FFB456",
		"=	c #FFD247",
		"-	c #FFBE3B",
		";	c #FFA633",
		">	c #FFB555",
		",	c #FFC54E",
		"'	c #FFC94D",
		")	c #FFCA4D",
		"!	c #FFC442",
		"~	c #FFB337",
		"{	c #FFB554",
		"]	c #FFB451",
		"^	c #FFA837",
		"/	c #FFA22A",
		"(	c #FFA32B",
		"_	c #FFA42B",
		":	c #F7BB62",
		"<	c #CADBB0",
		"[	c #C2DCB4",
		"}	c #C3DAAE",
		"|	c #C4DBAF",
		"1	c #AED9AE",
		"2	c #90D8AE",
		"3	c #F2BF6C",
		"4	c #A4F4EF",
		"5	c #98FDFF",
		"6	c #98FEFF",
		"7	c #9AFEFF",
		"8	c #73FCFF",
		"9	c #42FBFF",
		"0	c #00D7DF",
		"a	c #F2BF6B",
		"b	c #A7F3EA",
		"c	c #9BFBFF",
		"d	c #9DFBFF",
		"e	c #77FAFF",
		"f	c #48F9FF",
		"g	c #00D6DE",
		"h	c #47F8FF",
		"i	c #1BE4EB",
		"j	c #1AE4EB",
		"k	c #1FE6ED",
		"l	c #46F8FF",
		"m	c #A7F2EA",
		"n	c #F0C16E",
		"o	c #A6F4ED",
		"p	c #9AFCFF",
		"     ........           ",
		"   +@#.......$%&        ",
		"   +*=.......-;&        ",
		"   +*=.......-;&        ",
		"   +>,'')!$$$~;&        ",
		"   ++>>{]^/(((__        ",
		"   ++++:<[}}}|12        ",
		"   ++++3456667890       ",
		"   ++++abccccdef00      ",
		"   ++++abccccdef000     ",
		"   ++++abccccdefgggg    ",
		"   ++++abccccdehijijk   ",
		"   ++++abccccdehlllll   ",
		"   ++++abccccdehlllll   ",
		"   ++++abccccdehlllll   ",
		"   ++++abccccdehlllll   ",
		"   ++++abccccdehlllll   ",
		"   ++++amccccdehlllll   ",
		"   ++++noccccdehlllll   ",
		"        pccccdehlllll   ",
		"        cccccdehlllll   ",
		"        cccccdehlllll   ",
		"        cccccdehlllll   ",
		"        cccccdehlllll   "
};


